#!/bin/bash
sudo sed -i 's\Exec=env GDK_BACKEND=x11 /usr/bin/ulauncher --hide-window
\Exec=env WEBKIT_DISABLE_COMPOSITING_MODE=1 GDK_BACKEND=x11 /usr/bin/ulauncher --hide-window\g' /usr/share/applications/ulauncher.desktop
