#!/bin/bash

dconf dump / > ~/Documents/Private-Settings/all.dconf
cp ~/Templates/* ~/Documents/Private-Settings/templates -r
cd ~/Documents/Private-Settings
git add .
git commit -m "Settings upload"
git push
