#!/bin/bash
cd ~/Documents/Configuration/Korla-Plus && git pull
cd ~/Documents/Configuration/Lapidarium-Shell && git pull
cd ~/Documents/Configuration/Private-Settings && git pull
cd ~/Documents/Configuration/Some-Pretty-Boring-Shell-Scripts && git pull
cd ~/Documents/Quick-Installs && git pull
dnf-soft-sync
